name: GitHub Actions
on: 
  - push
jobs:
  build:
    runs-on: macos-latest
    steps:
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
          with:
            node-version: 18
        run: make install
        run: make test
        run: make lint
