name: GitHub Actions
on: 
  - push
  env:
    CI: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
          with:
            node-version: 18
      - run: make install
      - run: make test
      - run: make lint
