name: GitHub Actions

on: push

env:
  CI: true

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: 18
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: make install
      - run: make test
      - run: make lint
      - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true
  